---
- name: start docker
  become: yes
  hosts: all
  become_method: sudo
  become_user: root

  vars:
    secure: true
    redhat_url: "https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-rhel70-3.4.2.tgz"
    amazon_url: "https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-amazon-3.4.2.tgz"

  roles:
    - mongodb
    - docker