- name: start mysql
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  
  roles:
    - mysql
  vars:
    rpm: "http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm"
